### ISSUE TITLE
Document how to use "aar" artifacts with version catalogs

### ISSUE THREAD

**Issue by nikclayton** [mikepenz/Android-Iconics#639]
## About this issue

The documentation doesn't cover how to use the libraries with Gradle version catalogs. Ordinarily this would be straightforward, but it's made more complicated because Gradle version catalogs don't support the "aar" artifact type.

So if you have something like this in `libs.versions.toml`:

```toml
[versions]
# ...
material-iconics = "5.4.0"
material-typeface-outlined = "4.0.0.1-kotlin"
# ...

[libraries]
# ...
material-iconics = { module = "com.mikepenz:iconics-core", version.ref="material-iconics" }
material-typeface-outlined = { module = "com.mikepenz:google-material-typeface-outlined", version.ref = "material-typeface-outlined" }
# ...
```

You must add `{ artifact { type = "aar" } }` after the relevant `implementation`, like this:

```
    implementation(libs.material.iconics)
    implementation(libs.material.typeface.outlined) { artifact { type = "aar" } }
```

Hope that's helpful.

## Checklist

- [x] Searched for [similar issues](https://github.com/mikepenz/Android-Iconics/issues)
- [x] Checked out the [sample application](https://github.com/mikepenz/Android-Iconics/tree/develop/app)
- [x] Read the [README](https://github.com/mikepenz/Android-Iconics/blob/develop/README.md)
- [x] Checked out the [CHANGELOG](https://github.com/mikepenz/Android-Iconics/releases)
- [x] Read the [FAQ](https://github.com/mikepenz/Android-Iconics/blob/develop/FAQ.md)
- [x] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/Android-Iconics/blob/develop/MIGRATION.md)
